### ISSUE TITLE
Anrede sollte einheitlich sein

### ISSUE THREAD

**Issue by behrends** [pfeil13/JavaProjekt_Gruppe8#2]
Manchmal wird `du` und anderen Stellen `Sie` verwendet. Dies sollte einheitlich sein. Und `Sie` wird groß geschrieben ;-)
https://github.com/pfeil13/JavaProjekt_Gruppe8/blob/53889f363b9da2b35237feffb1d5d329153c75b0/src/Menue.java#L107

**Comment by Tobi1495** [comment]
edit: wir einigen uns auf du
