### ISSUE TITLE
Code nicht einheitlich eingerückt

### ISSUE THREAD

**Issue by behrends** [pfeil13/JavaProjekt_Gruppe8#6]
https://github.com/pfeil13/JavaProjekt_Gruppe8/blob/53889f363b9da2b35237feffb1d5d329153c75b0/src/WriteCatalog.java#L43-L48

**Comment by Tobi1495** [comment]
Guten Abend Herr Prof. Dr. Behrends,

ich habe nachgesehen. Tatsächlich sieht der Code bei mir anders aus.
Dennoch habe ich es unter "Reformat Code" nochmals überprüft und comitted!

Viele Grüße,
Tobias Hess
